version: '3'

services:
  proxy:
    image: nginx:1.17.10
    container_name: proxy
    depends_on:
      - back
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  back:
    image: back
    container_name: back
    build:
      context: ./back
    restart: on-failure

  front:
    image: front
    container_name: front
    build:
      context: ./front
    restart: on-failure